# Generated by Django 5.1.4 on 2025-07-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile_old_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('address', models.CharField(default='', max_length=500)),
                ('governrate', models.CharField(choices=[('1', 'Qena'), ('2', 'Sohag'), ('3', 'Cairo')], default='', max_length=50)),
                ('open_at', models.TimeField()),
                ('close_at', models.TimeField()),
                ('phone', models.CharField(default='', max_length=20)),
                ('watts_app', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('active_status', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
