# Generated by Django 5.1.4 on 2025-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_vendor_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_not_availabe',
            field=models.BooleanField(default=False),
        ),
    ]
