# Generated by Django 5.1.4 on 2025-07-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_is_not_availabe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_not_availabe',
            new_name='is_not_available',
        ),
    ]
