# Generated by Django 5.1.4 on 2025-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_is_not_availabe_product_is_not_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('1', 'متنوع'), ('2', 'اكسسوارات'), ('3', 'مطاعم')], default='', max_length=50),
        ),
    ]
