# Generated by Django 5.1.4 on 2025-07-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_vendor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('1', 'متنوع'), ('2', 'اكسسوارات'), ('3', 'مطاعم'), ('4', 'صيدليات'), ('5', 'ملابس')], default='', max_length=50),
        ),
    ]
