# Generated by Django 5.1.4 on 2025-07-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_vendor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('متنوع', 'متنوع'), ('اكسسوارات', 'اكسسوارات'), ('مطاعم', 'مطاعم'), ('صيدليات', 'صيدليات'), ('ملابس', 'ملابس')], default='', max_length=50),
        ),
    ]
